<a href="https://colab.research.google.com/github/melbinmv/Movie-Recommendation-Chatbot/blob/main/TMDB_Movie_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Libraries
import pandas as pd

In [2]:
#get TMDB dataset from drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#Read TMDB dataset from drive
movie_dat = pd.read_csv('/content/drive/MyDrive/dev/TMDB_movie_dataset_v11.csv')
movie_dat

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076824,705578,Girls of Bangbros 74: Kelsi Monroe,0.000,0,Released,2018-01-26,0,238,True,NaN,...,Girls of Bangbros 74: Kelsi Monroe,NaN,1.349,/otKXG6pkFHqbupHd2jxJB0z00rL.jpg,NaN,NaN,Bang Bros Productions,United States of America,English,"compilation, brunette, star showcase"
1076825,705581,West By North,0.000,0,Released,1977-01-01,0,25,False,NaN,...,West By North,"""The direction of Western Culture's advance ha...",0.600,/760VjPlVaSIu7EaidxzvEG4mHjy.jpg,NaN,NaN,NaN,NaN,No Language,NaN
1076826,705582,#BigBootyHoes,0.000,0,Released,2018-07-13,0,120,True,NaN,...,#BigBootyHoes,Blonde Beauty Madelyn Moore Sucks His Cock and...,0.600,/lnqQPS6262isUz81n9UqP4j7Xiy.jpg,HASH TAG THAT ASS!,NaN,Devil's Film,United States of America,English,NaN
1076827,705583,My Best Friend's Sister,0.000,0,Released,NaN,0,36,False,NaN,...,My Best Friend's Sister,Documenting three sets of sisters.,0.600,/lG1a0I1gI97lFkYYXy6VLEkPMA0.jpg,NaN,NaN,NaN,NaN,NaN,NaN
1076828,1329338,Berryz工房サマーコンサートツアー2006『夏夏！〜あなたを好きになる三原則〜』,0.000,0,Released,2006-08-13,0,0,False,NaN,...,Berryz工房サマーコンサートツアー2006『夏夏！〜あなたを好きになる三原則〜』,NaN,0.600,/9ZdOj3p165mjvjOr8nHdx2HD3nx.jpg,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Dataset columns
movie_dat.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='object')

In [ ]:
# Selecting the columns which are needed for the analysis
movie_dat = movie_dat[['id','title','vote_average','vote_count','release_date','overview','original_language','genres','keywords','tagline','revenue','budget','status','popularity']]
movie_dat

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity
0,27205,Inception,8.364,34495,2010-07-15,"Cobb, a skilled thief who commits corporate es...",en,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...",Your mind is the scene of the crime.,825532764,160000000,Released,83.952
1,157336,Interstellar,8.417,32571,2014-11-05,The adventures of a group of explorers who mak...,en,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",Mankind was born on Earth. It was never meant ...,701729206,165000000,Released,140.241
2,155,The Dark Knight,8.512,30619,2008-07-16,Batman raises the stakes in his war on crime. ...,en,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...",Welcome to a world without rules.,1004558444,185000000,Released,130.643
3,19995,Avatar,7.573,29815,2009-12-15,"In the 22nd century, a paraplegic Marine is di...",en,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...",Enter the world of Pandora.,2923706026,237000000,Released,79.932
4,24428,The Avengers,7.710,29166,2012-04-25,When an unexpected enemy emerges and threatens...,en,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Some assembly required.,1518815515,220000000,Released,98.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076824,705578,Girls of Bangbros 74: Kelsi Monroe,0.000,0,2018-01-26,NaN,en,NaN,"compilation, brunette, star showcase",NaN,0,0,Released,1.349
1076825,705581,West By North,0.000,0,1977-01-01,"""The direction of Western Culture's advance ha...",en,NaN,NaN,NaN,0,0,Released,0.600
1076826,705582,#BigBootyHoes,0.000,0,2018-07-13,Blonde Beauty Madelyn Moore Sucks His Cock and...,en,NaN,NaN,HASH TAG THAT ASS!,0,0,Released,0.600
1076827,705583,My Best Friend's Sister,0.000,0,NaN,Documenting three sets of sisters.,en,NaN,NaN,NaN,0,0,Released,0.600
1076828,1329338,Berryz工房サマーコンサートツアー2006『夏夏！〜あなたを好きになる三原則〜』,0.000,0,2006-08-13,NaN,ja,NaN,NaN,NaN,0,0,Released,0.600

In [ ]:
movie_dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1076829 entries, 0 to 1076828
Data columns (total 14 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   id                 1076829 non-null  int64
 1   title              1076816 non-null  object
 2   vote_average       1076829 non-null  float64
 3   vote_count         1076829 non-null  int64
 4   release_date       923803 non-null   object
 5   overview           873162 non-null   object
 6   original_language  1076829 non-null  object
 7   genres             661342 non-null   object
 8   keywords           300741 non-null   object
 9   tagline            153341 non-null   object
 10  revenue            1076829 non-null  int64
 11  budget             1076829 non-null  int64
 12  status             1076829 non-null  object
 13  popularity         1076829 non-null  float64
dtypes: float64(2), int64(4), object(8)
memory usage: 115.0+ MB

In [ ]:
# Finding the null values
movie_dat.isnull().sum()

id                        0
title                    13
vote_average              0
vote_count                0
release_date         153026
overview             203667
original_language         0
genres               415487
keywords             776088
tagline              923488
revenue                   0
budget                    0
status                    0
popularity                0
dtype: int64

In [ ]:
# Show the movies whose title is null
movie_dat[movie_dat['title'].isnull()]
# Delete all the titles with null values
movie_dat = movie_dat.dropna(subset=['title'])

In [ ]:
# Re-checking for null values again in the title
movie_dat.isnull().sum()

id                        0
title                     0
vote_average              0
vote_count                0
release_date         153017
overview             203658
original_language         0
genres               415479
keywords             776076
tagline              923475
revenue                   0
budget                    0
status                    0
popularity                0
dtype: int64

In [ ]:
# Creating a new dataframe to store movies that are not in english
movie_not_english = movie_dat[movie_dat['original_language'] != 'en']
movie_not_english

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity
81,496243,Parasite,8.515,16430,2019-05-30,"All unemployed, Ki-taek's family takes peculia...",ko,"Comedy, Thriller, Drama","dark comedy, private lessons, birthday party, ...",Act like you own the place.,257591776,11363000,Released,64.627
89,77338,The Intouchables,8.277,16083,2011-11-02,A true story of two men who should never have ...,fr,"Drama, Comedy","friendship, male friendship, based on true sto...",Sometimes you have to reach into someone else'...,426588510,13000000,Released,41.656
107,129,Spirited Away,8.539,14913,2001-07-20,"A young girl, Chihiro, becomes trapped in a st...",ja,"Animation, Family, Fantasy","witch, parent child relationship, darkness, ba...",NaN,274925095,19000000,Released,68.024
181,637,Life Is Beautiful,8.455,12218,1997-12-20,A touching story of an Italian book seller of ...,it,"Comedy, Drama","dying and death, bookshop, love of one's life,...","An unforgettable fable that proves love, famil...",230098753,20000000,Released,39.478
234,194,Amélie,7.905,10750,2001-04-25,"At a tiny Parisian café, the adorable yet pain...",fr,"Comedy, Romance","daughter, paris, france, love triangle, photog...",One person can change your life forever.,173921954,10000000,Released,42.494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076809,705553,Bardo,0.000,0,2019-06-30,NaN,fr,NaN,NaN,NaN,0,0,Released,0.600
1076814,705562,Concrete,0.000,0,2013-06-16,Vienna in the late 90s. VHS footage reveals th...,de,Drama,"cocaine, beer, tragedy, juvenile delinquent, d...",NaN,0,0,Released,0.600
1076819,705570,Hello! Project 2017 Hina Fes ~℃-ute Premium~,0.000,0,2017-03-26,Hello! Project concert held at Makuhari Messe ...,ja,NaN,NaN,NaN,0,0,Released,0.628
1076820,705572,Hello! Project 2017 Hina Fes ~Morning Musume.'...,0.000,0,2017-03-26,Hello! Project concert held at Makuhari Messe ...,ja,NaN,NaN,NaN,0,0,Released,0.628
1076828,1329338,Berryz工房サマーコンサートツアー2006『夏夏！〜あなたを好きになる三原則〜』,0.000,0,2006-08-13,NaN,ja,NaN,NaN,NaN,0,0,Released,0.600

In [ ]:
# Remove movies with titles not in english from original dataframe
movie_dat = movie_dat[movie_dat['original_language'] == 'en']
movie_dat

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity
0,27205,Inception,8.364,34495,2010-07-15,"Cobb, a skilled thief who commits corporate es...",en,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...",Your mind is the scene of the crime.,825532764,160000000,Released,83.952
1,157336,Interstellar,8.417,32571,2014-11-05,The adventures of a group of explorers who mak...,en,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",Mankind was born on Earth. It was never meant ...,701729206,165000000,Released,140.241
2,155,The Dark Knight,8.512,30619,2008-07-16,Batman raises the stakes in his war on crime. ...,en,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...",Welcome to a world without rules.,1004558444,185000000,Released,130.643
3,19995,Avatar,7.573,29815,2009-12-15,"In the 22nd century, a paraplegic Marine is di...",en,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...",Enter the world of Pandora.,2923706026,237000000,Released,79.932
4,24428,The Avengers,7.710,29166,2012-04-25,When an unexpected enemy emerges and threatens...,en,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Some assembly required.,1518815515,220000000,Released,98.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076823,705576,Moments Ago,0.000,0,1969-01-01,"""Nancy and I were aware that our daughter Jenn...",en,NaN,NaN,NaN,0,0,Released,0.600
1076824,705578,Girls of Bangbros 74: Kelsi Monroe,0.000,0,2018-01-26,NaN,en,NaN,"compilation, brunette, star showcase",NaN,0,0,Released,1.349
1076825,705581,West By North,0.000,0,1977-01-01,"""The direction of Western Culture's advance ha...",en,NaN,NaN,NaN,0,0,Released,0.600
1076826,705582,#BigBootyHoes,0.000,0,2018-07-13,Blonde Beauty Madelyn Moore Sucks His Cock and...,en,NaN,NaN,HASH TAG THAT ASS!,0,0,Released,0.600
1076827,705583,My Best Friend's Sister,0.000,0,NaN,Documenting three sets of sisters.,en,NaN,NaN,NaN,0,0,Released,0.600

In [ ]:
# Drop movies with overview is None
movie_not_english = movie_not_english.dropna(subset=['overview'])
#Drop movies with status Planned, Rumored and Canceled
movie_not_english.drop(movie_not_english[movie_not_english['status'].isin(['Planned', 'Rumored', 'Canceled'])].index, inplace=True)
# Drop movies with release date is None
movie_not_english = movie_not_english.dropna(subset=['release_date'])

<ipython-input-13-3466b92e1b76>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_not_english.drop(movie_not_english[movie_not_english['status'].isin(['Planned', 'Rumored', 'Canceled'])].index, inplace=True)

In [ ]:
movie_not_english.isnull().sum()

id                        0
title                     0
vote_average              0
vote_count                0
release_date              0
overview                  0
original_language         0
genres                60233
keywords             208073
tagline              272168
revenue                   0
budget                    0
status                    0
popularity                0
dtype: int64

In [ ]:
movie_not_english.shape

(299607, 14)

In [ ]:
# Checking for null values again
movie_dat.isnull().sum()

id                        0
title                     0
vote_average              0
vote_count                0
release_date         100698
overview              25651
original_language         0
genres               269657
keywords             404634
tagline              460378
revenue                   0
budget                    0
status                    0
popularity                0
dtype: int64

In [ ]:
#Delete the movies with overview is None
movie_dat = movie_dat.dropna(subset=['overview'])
movie_dat

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity
0,27205,Inception,8.364,34495,2010-07-15,"Cobb, a skilled thief who commits corporate es...",en,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...",Your mind is the scene of the crime.,825532764,160000000,Released,83.952
1,157336,Interstellar,8.417,32571,2014-11-05,The adventures of a group of explorers who mak...,en,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",Mankind was born on Earth. It was never meant ...,701729206,165000000,Released,140.241
2,155,The Dark Knight,8.512,30619,2008-07-16,Batman raises the stakes in his war on crime. ...,en,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...",Welcome to a world without rules.,1004558444,185000000,Released,130.643
3,19995,Avatar,7.573,29815,2009-12-15,"In the 22nd century, a paraplegic Marine is di...",en,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...",Enter the world of Pandora.,2923706026,237000000,Released,79.932
4,24428,The Avengers,7.710,29166,2012-04-25,When an unexpected enemy emerges and threatens...,en,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Some assembly required.,1518815515,220000000,Released,98.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076821,705573,953,0.000,0,2020-05-17,A short film about the passion for music.,en,"Documentary, Music",NaN,NaN,0,0,Released,0.600
1076823,705576,Moments Ago,0.000,0,1969-01-01,"""Nancy and I were aware that our daughter Jenn...",en,NaN,NaN,NaN,0,0,Released,0.600
1076825,705581,West By North,0.000,0,1977-01-01,"""The direction of Western Culture's advance ha...",en,NaN,NaN,NaN,0,0,Released,0.600
1076826,705582,#BigBootyHoes,0.000,0,2018-07-13,Blonde Beauty Madelyn Moore Sucks His Cock and...,en,NaN,NaN,HASH TAG THAT ASS!,0,0,Released,0.600
1076827,705583,My Best Friend's Sister,0.000,0,NaN,Documenting three sets of sisters.,en,NaN,NaN,NaN,0,0,Released,0.600

In [ ]:
#Show movies with missing release date
movie_dat[movie_dat['release_date'].isnull()]

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity
15882,1091834,Return,6.98,124,NaN,RETURN tells the story of a retired Green Bere...,en,NaN,NaN,A retired Green Beret returns to Vietnam with ...,0,0,Released,4.444
29985,614840,Box,5.00,44,NaN,"A group of friends try to defeat an evil king,...",en,NaN,NaN,Box Rocks!,5,2,Released,1.553
33518,823711,kino-react,6.20,37,NaN,test api requests for kinosakartvelo movie web...,en,NaN,NaN,NaN,0,0,Released,1.307
36237,598652,Hey Qween - Holigay Special,5.40,33,NaN,Let’s get SICK’NING for the Holidays! RuPaul’s...,en,NaN,NaN,NaN,0,0,Released,1.250
39806,496306,Movies,4.40,28,NaN,action movies,en,NaN,NaN,NaN,0,0,Released,1.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076788,705591,The Game,0.00,0,NaN,Four individuals play a game of a lifetime wit...,en,NaN,NaN,Are you ready to play the game?,0,711,Released,0.600
1076789,705593,Lyrics to Dying Rebirth,0.00,0,NaN,"Kasper, a combat reporter on sabbatical is dra...",en,NaN,NaN,Love Has A Price,0,0,Released,0.600
1076810,705556,I Have Seen The Future: A Tour of the 1939 New...,0.00,0,NaN,I Have Seen The Future: A Tour of the 1939 New...,en,Documentary,NaN,NaN,0,0,Released,0.600
1076811,705557,Te Whare: The House,0.00,0,NaN,A present day recreation of Aotearoa New Zeala...,en,NaN,NaN,NaN,0,0,Released,0.600
1076827,705583,My Best Friend's Sister,0.00,0,NaN,Documenting three sets of sisters.,en,NaN,NaN,NaN,0,0,Released,0.600

In [ ]:
#Find the unique values in the column status
movie_dat['status'].unique()

array(['Released', 'Planned', 'Post Production', 'Rumored',
       'In Production', 'Canceled'], dtype=object)

In [ ]:
#Drop movies with status Planned, Rumored and Canceled
movie_dat.drop(movie_dat[movie_dat['status'].isin(['Planned', 'Rumored', 'Canceled'])].index, inplace=True)
movie_dat

<ipython-input-20-23e049432aec>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_dat.drop(movie_dat[movie_dat['status'].isin(['Planned', 'Rumored', 'Canceled'])].index, inplace=True)

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity
0,27205,Inception,8.364,34495,2010-07-15,"Cobb, a skilled thief who commits corporate es...",en,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...",Your mind is the scene of the crime.,825532764,160000000,Released,83.952
1,157336,Interstellar,8.417,32571,2014-11-05,The adventures of a group of explorers who mak...,en,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",Mankind was born on Earth. It was never meant ...,701729206,165000000,Released,140.241
2,155,The Dark Knight,8.512,30619,2008-07-16,Batman raises the stakes in his war on crime. ...,en,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...",Welcome to a world without rules.,1004558444,185000000,Released,130.643
3,19995,Avatar,7.573,29815,2009-12-15,"In the 22nd century, a paraplegic Marine is di...",en,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...",Enter the world of Pandora.,2923706026,237000000,Released,79.932
4,24428,The Avengers,7.710,29166,2012-04-25,When an unexpected enemy emerges and threatens...,en,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Some assembly required.,1518815515,220000000,Released,98.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076821,705573,953,0.000,0,2020-05-17,A short film about the passion for music.,en,"Documentary, Music",NaN,NaN,0,0,Released,0.600
1076823,705576,Moments Ago,0.000,0,1969-01-01,"""Nancy and I were aware that our daughter Jenn...",en,NaN,NaN,NaN,0,0,Released,0.600
1076825,705581,West By North,0.000,0,1977-01-01,"""The direction of Western Culture's advance ha...",en,NaN,NaN,NaN,0,0,Released,0.600
1076826,705582,#BigBootyHoes,0.000,0,2018-07-13,Blonde Beauty Madelyn Moore Sucks His Cock and...,en,NaN,NaN,HASH TAG THAT ASS!,0,0,Released,0.600
1076827,705583,My Best Friend's Sister,0.000,0,NaN,Documenting three sets of sisters.,en,NaN,NaN,NaN,0,0,Released,0.600

In [ ]:
movie_dat.isnull().sum()

id                        0
title                     0
vote_average              0
vote_count                0
release_date          85167
overview                  0
original_language         0
genres               248716
keywords             379505
tagline              431662
revenue                   0
budget                    0
status                    0
popularity                0
dtype: int64

In [ ]:
movie_with_nodates = movie_dat[movie_dat['release_date'].isna()]
print(f"Movies with missing release dates: {len(movie_with_nodates)} ({len(movie_with_nodates)/len(movie_dat)*100:.2f}%)")

Movies with missing release dates: 85167 (15.36%)

In [ ]:
movie_dat = movie_dat[~movie_dat['release_date'].isna()]
movie_dat

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity
0,27205,Inception,8.364,34495,2010-07-15,"Cobb, a skilled thief who commits corporate es...",en,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...",Your mind is the scene of the crime.,825532764,160000000,Released,83.952
1,157336,Interstellar,8.417,32571,2014-11-05,The adventures of a group of explorers who mak...,en,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",Mankind was born on Earth. It was never meant ...,701729206,165000000,Released,140.241
2,155,The Dark Knight,8.512,30619,2008-07-16,Batman raises the stakes in his war on crime. ...,en,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...",Welcome to a world without rules.,1004558444,185000000,Released,130.643
3,19995,Avatar,7.573,29815,2009-12-15,"In the 22nd century, a paraplegic Marine is di...",en,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...",Enter the world of Pandora.,2923706026,237000000,Released,79.932
4,24428,The Avengers,7.710,29166,2012-04-25,When an unexpected enemy emerges and threatens...,en,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Some assembly required.,1518815515,220000000,Released,98.082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076818,705568,Nemesis Revisited,0.000,0,2013-04-13,A behind the scenes look at Star Trek: Nemesis,en,Documentary,NaN,NaN,0,0,Released,0.600
1076821,705573,953,0.000,0,2020-05-17,A short film about the passion for music.,en,"Documentary, Music",NaN,NaN,0,0,Released,0.600
1076823,705576,Moments Ago,0.000,0,1969-01-01,"""Nancy and I were aware that our daughter Jenn...",en,NaN,NaN,NaN,0,0,Released,0.600
1076825,705581,West By North,0.000,0,1977-01-01,"""The direction of Western Culture's advance ha...",en,NaN,NaN,NaN,0,0,Released,0.600
1076826,705582,#BigBootyHoes,0.000,0,2018-07-13,Blonde Beauty Madelyn Moore Sucks His Cock and...,en,NaN,NaN,HASH TAG THAT ASS!,0,0,Released,0.600

In [ ]:
movie_dat.isnull().sum()

id                        0
title                     0
vote_average              0
vote_count                0
release_date              0
overview                  0
original_language         0
genres               181016
keywords             302803
tagline              362670
revenue                   0
budget                    0
status                    0
popularity                0
dtype: int64

In [ ]:
# Sort These Movies by Popularity (Ascending Order)
movie_with_nodates = movie_with_nodates.sort_values(by="popularity", ascending=True)
movie_with_nodates

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity
582671,1300933,Untitled Vampire Short Film,0.0,0,NaN,A hunter travels through the Norwegian wildern...,en,NaN,NaN,NaN,0,0,Released,0.000
540419,1311103,Assault: The World’s Most Violent Collection o...,0.0,0,NaN,The Worlds Most Violent Collection Of Real Str...,en,Documentary,NaN,Bling Bling Approved,0,0,Released,0.000
540422,1311106,Breath,0.0,0,NaN,"A short film shot over a week in Casey County,...",en,NaN,NaN,NaN,0,0,Released,0.000
540425,1311109,Capture,0.0,0,NaN,A distressed woman is on the run after stealin...,en,"Science Fiction, Drama",NaN,NaN,0,0,Released,0.000
540427,1311111,The Enigma Within,0.0,0,NaN,The mysterious Lisa Parker becomes the focal p...,en,NaN,NaN,NaN,0,0,In Production,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
436526,931285,Mortal Kombat 2,0.0,0,NaN,A sequel to the 2021 film 'Mortal Kombat'.,en,"Action, Fantasy, Adventure","martial arts, based on video game",NaN,0,0,In Production,11.899
878576,369826,La hora de la libertad ha sonado,0.0,0,NaN,It is a historical document of imperialism in ...,en,NaN,NaN,NaN,0,0,Released,15.059
744259,574475,Final Destination 6,0.0,0,NaN,Sixth installment in the Final Destination fra...,en,"Horror, Mystery",NaN,NaN,0,0,In Production,16.016
441179,1025138,Blacked Raw 56,0.0,0,NaN,"BLACKED.com is proud to present ""BLACKED RAW""....",en,NaN,NaN,NaN,0,0,Released,16.846
424468,911916,Spider-Man: Beyond the Spider-Verse,0.0,0,NaN,The final chapter of Miles Morales and the man...,en,"Animation, Action, Adventure, Science Fiction","new york city, superhero, based on comic, sequ...",NaN,0,0,In Production,22.674

In [ ]:
movie_with_nodates['null_count'] = movie_with_nodates.isna().sum(axis=1)
movies_with_most_nulls= movie_with_nodates.sort_values(by="null_count", ascending=False)

In [ ]:
movies_with_most_nulls.shape

(85167, 15)

In [ ]:
movies_with_most_nulls

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity,null_count
582671,1300933,Untitled Vampire Short Film,0.0,0,NaN,A hunter travels through the Norwegian wildern...,en,NaN,NaN,NaN,0,0,Released,0.00,4
924299,784275,McMahon Family XMas,0.0,0,NaN,An anthology of Christmas themed horror movies...,en,NaN,NaN,NaN,0,0,Released,0.60,4
925901,791603,Guest Booker with Gabe Sapolsky,0.0,0,NaN,IT’S JUNE 2006 AND ECW WILL BE RAMPING UP AGAI...,en,NaN,NaN,NaN,0,0,Released,0.60,4
925900,791602,Guest Booker with Dutch Mantell,0.0,0,NaN,"On January 4, 2009 TNA was to give birth to a ...",en,NaN,NaN,NaN,0,0,Released,0.60,4
925899,791601,Guest Booker with Bruce Prichard,0.0,0,NaN,That’s our guest’s take on the happenings in M...,en,NaN,NaN,NaN,0,0,Released,0.60,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315181,1129093,Spin the Wheel,8.0,1,NaN,"On the eve of the Apocalypse, a motley group o...",en,"Horror, Thriller","supernatural, end of the world, devil, ensembl...",Killing time at the end of the world.,0,0,Released,0.87,1
505339,1274472,The Fairyhouse,0.0,0,NaN,At an all time low in her personal and profess...,en,"Fantasy, Drama","fairy, father, straight relationship, childhoo...",magic finds you,0,0,Released,1.25,1
616401,1155945,Nalb Noum,0.0,0,NaN,An arcane massacre on the Black community is u...,en,"Horror, Animation",short film,A Myth Awakened,0,0,Released,0.60,1
623350,1111203,Left Standing,0.0,0,NaN,"A WWI veteran, John Mills (Jack Marshall), wit...",en,"War, Drama, History","post-traumatic stress disorder (ptsd), dementi...","After war, there's no telling how fragile your...",0,0,Released,0.00,1
682220,1168071,She's Not Alone,0.0,0,NaN,"She's Not Alone is a social enterprise short, ...",en,"Documentary, Drama","feminist, social justice","She's Not Alone is a social enterprise short, ...",0,6,Released,0.60,1

In [ ]:
# Number of movies with null_count is 4
movies_with_most_nulls[movies_with_most_nulls['null_count'] == 4]

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity,null_count
582671,1300933,Untitled Vampire Short Film,0.0,0,NaN,A hunter travels through the Norwegian wildern...,en,NaN,NaN,NaN,0,0,Released,0.0,4
924299,784275,McMahon Family XMas,0.0,0,NaN,An anthology of Christmas themed horror movies...,en,NaN,NaN,NaN,0,0,Released,0.6,4
925901,791603,Guest Booker with Gabe Sapolsky,0.0,0,NaN,IT’S JUNE 2006 AND ECW WILL BE RAMPING UP AGAI...,en,NaN,NaN,NaN,0,0,Released,0.6,4
925900,791602,Guest Booker with Dutch Mantell,0.0,0,NaN,"On January 4, 2009 TNA was to give birth to a ...",en,NaN,NaN,NaN,0,0,Released,0.6,4
925899,791601,Guest Booker with Bruce Prichard,0.0,0,NaN,That’s our guest’s take on the happenings in M...,en,NaN,NaN,NaN,0,0,Released,0.6,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501408,1270319,Bobby Came Home,0.0,0,NaN,"After going missing for several months, a woma...",en,NaN,NaN,NaN,0,0,Released,0.0,4
536862,1239946,In the Heat of the Night: Who Was Geli Bendl?,0.0,0,NaN,All eyes are on Sparta after an internationall...,en,NaN,NaN,NaN,0,0,Released,0.0,4
499512,1251484,Drone,0.0,0,NaN,Architecture student Emily becomes a victim of...,en,NaN,NaN,NaN,0,0,Released,0.0,4
536223,1235223,Prima che il sole tramonti,0.0,0,NaN,Italian horror movie from 1976.,en,NaN,NaN,NaN,0,0,Released,0.0,4
537004,1239418,LEXICON,0.0,0,NaN,An inspiring short film that celebrates the un...,en,NaN,NaN,NaN,0,0,Released,0.0,4

In [ ]:
# Drop the movies with null_count = 4
movie_with_nodates = movie_with_nodates.drop(movies_with_most_nulls[movies_with_most_nulls['null_count'] == 4].index)
movie_with_nodates

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity,null_count
540419,1311103,Assault: The World’s Most Violent Collection o...,0.0,0,NaN,The Worlds Most Violent Collection Of Real Str...,en,Documentary,NaN,Bling Bling Approved,0,0,Released,0.000,2
540425,1311109,Capture,0.0,0,NaN,A distressed woman is on the run after stealin...,en,"Science Fiction, Drama",NaN,NaN,0,0,Released,0.000,3
540539,1311281,1857 Diary: The Hidden Pages,0.0,0,NaN,A film which reveals the role of Maharshi Swam...,en,NaN,NaN,A film which reveals the role of Maharshi Swam...,0,0,Released,0.000,3
540553,1311296,Ciudad Evita,0.0,0,NaN,Carlos takes his grandchildren to Ciudad Evita...,en,NaN,NaN,Can a place be a real space and a memory at th...,0,0,Released,0.000,3
540554,1311297,The Tale of the Dog,0.0,0,NaN,The Tale of the Dog is a documentary film prod...,en,NaN,NaN,The Tale of the Dog tells the previously-untol...,0,0,Released,0.000,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455942,1041081,Gale - Stay Away From Oz,0.0,0,NaN,Long gone are the days of emerald cities and y...,en,Horror,NaN,NaN,0,0,Post Production,8.276,3
358767,1084242,Zootopia 2,0.0,0,NaN,Sequel to the 2016 animated film Zootopia. Plo...,en,"Animation, Comedy, Family",NaN,NaN,0,0,In Production,9.816,3
436526,931285,Mortal Kombat 2,0.0,0,NaN,A sequel to the 2021 film 'Mortal Kombat'.,en,"Action, Fantasy, Adventure","martial arts, based on video game",NaN,0,0,In Production,11.899,2
744259,574475,Final Destination 6,0.0,0,NaN,Sixth installment in the Final Destination fra...,en,"Horror, Mystery",NaN,NaN,0,0,In Production,16.016,3
424468,911916,Spider-Man: Beyond the Spider-Verse,0.0,0,NaN,The final chapter of Miles Morales and the man...,en,"Animation, Action, Adventure, Science Fiction","new york city, superhero, based on comic, sequ...",NaN,0,0,In Production,22.674,2

In [ ]:
print(f"Movies with missing release dates: {len(movie_with_nodates)} ({len(movie_with_nodates)/len(movie_dat)*100:.2f}%)")

Movies with missing release dates: 31452 (6.70%)

In [ ]:
# Merge the Remaining Movies Back into the Main Dataset
movie_dat = pd.concat([movie_dat, movie_with_nodates, movie_not_english], ignore_index=True)
movie_dat

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity,null_count
0,27205,Inception,8.364,34495,2010-07-15,"Cobb, a skilled thief who commits corporate es...",en,"Action, Science Fiction, Adventure","rescue, mission, dream, airplane, paris, franc...",Your mind is the scene of the crime.,825532764,160000000,Released,83.952,NaN
1,157336,Interstellar,8.417,32571,2014-11-05,The adventures of a group of explorers who mak...,en,"Adventure, Drama, Science Fiction","rescue, future, spacecraft, race against time,...",Mankind was born on Earth. It was never meant ...,701729206,165000000,Released,140.241,NaN
2,155,The Dark Knight,8.512,30619,2008-07-16,Batman raises the stakes in his war on crime. ...,en,"Drama, Action, Crime, Thriller","joker, sadism, chaos, secret identity, crime f...",Welcome to a world without rules.,1004558444,185000000,Released,130.643,NaN
3,19995,Avatar,7.573,29815,2009-12-15,"In the 22nd century, a paraplegic Marine is di...",en,"Action, Adventure, Fantasy, Science Fiction","future, society, culture clash, space travel, ...",Enter the world of Pandora.,2923706026,237000000,Released,79.932,NaN
4,24428,The Avengers,7.710,29166,2012-04-25,When an unexpected enemy emerges and threatens...,en,"Science Fiction, Action, Adventure","new york city, superhero, shield, based on com...",Some assembly required.,1518815515,220000000,Released,98.082,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
800307,705617,Hips Don't Lie,0.000,0,2020-12-31,A comedy about the sexy and lovely growth of a...,ko,Comedy,NaN,NaN,0,0,Released,1.400,NaN
800308,705552,James Tissot: L'étoffe d'un peintre,0.000,0,2020-04-05,"A movie about James Tissot (1836-1902), a Fren...",fr,"Documentary, TV Movie","painter, art, art history, fine art",NaN,0,0,Released,0.662,NaN
800309,705562,Concrete,0.000,0,2013-06-16,Vienna in the late 90s. VHS footage reveals th...,de,Drama,"cocaine, beer, tragedy, juvenile delinquent, d...",NaN,0,0,Released,0.600,NaN
800310,705570,Hello! Project 2017 Hina Fes ~℃-ute Premium~,0.000,0,2017-03-26,Hello! Project concert held at Makuhari Messe ...,ja,NaN,NaN,NaN,0,0,Released,0.628,NaN
800311,705572,Hello! Project 2017 Hina Fes ~Morning Musume.'...,0.000,0,2017-03-26,Hello! Project concert held at Makuhari Messe ...,ja,NaN,NaN,NaN,0,0,Released,0.628,NaN

In [ ]:
movie_dat.isnull().sum()

id                        0
title                     0
vote_average              0
vote_count                0
release_date          31452
overview                  0
original_language         0
genres               255234
keywords             533863
tagline              650115
revenue                   0
budget                    0
status                    0
popularity                0
null_count           768860
dtype: int64

In [ ]:
# Show Duplicates
movie_dat[movie_dat.duplicated()]

,id,title,vote_average,vote_count,release_date,overview,original_language,genres,keywords,tagline,revenue,budget,status,popularity,null_count
123937,1192952,Rowntree vs Cadbury: A Rivalry Through Time,10.0,1,2023-10-13,Eggwork Media's latest historical documentary ...,en,"Documentary, History",NaN,Reformers. Pioneers. Adversaries.,0,2436,Released,2.300,NaN
132992,1199990,The Undead,10.0,1,2023-10-27,At the end of times a dysfunctional family tak...,en,"Horror, Thriller","undead, religion, dead children, religious horror",The end is just the beginning,0,420000,Released,1.400,NaN
140146,1214170,Frienemies,10.0,1,2013-07-15,"Four friends Mike, Shane, Diego and Matt plan ...",en,"Comedy, Action, Thriller",NaN,Friendships come and go.,0,0,Released,0.600,NaN
149165,1260267,My First Porno 6,6.0,1,2016-12-20,Sasha Jones: New girl for hire! Alice Romain:...,en,NaN,european,NaN,0,0,Released,0.000,NaN
149186,1260267,My First Porno 6,6.0,1,2016-12-20,Sasha Jones: New girl for hire! Alice Romain:...,en,NaN,european,NaN,0,0,Released,0.000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
698017,1211561,a beautiful day of September,0.0,0,2023-11-30,Mihalis wakes up on another day of misery and ...,el,Drama,NaN,NaN,0,0,Released,1.400,NaN
701632,1192941,Ekda Yeun Tar Bagha,0.0,0,2023-11-24,upcoming marathi film,mr,Comedy,NaN,YOU WOULDN'T GO BACK,0,0,Post Production,1.072,NaN
701634,1192944,Christmas Concert with Odd Nordstoga,0.0,0,2016-12-23,Odd Nordstoga invites you to an intimate and b...,no,Music,christmas concert,NaN,0,0,Released,0.600,NaN
701635,1192953,"Memoir of Miss Kuan, A Celebrated Sex Worker",0.0,0,2006-12-31,"In 1997, the Taipei City Council abolished the...",zh,Documentary,NaN,NaN,0,0,Released,0.600,NaN
701637,1192955,Happy Man's Diaries,0.0,0,2011-05-18,"In St. Petersburg, in a house near the Neva, a...",ru,Documentary,NaN,NaN,0,0,Released,0.600,NaN

In [ ]:
# Drop duplicates
movie_dat = movie_dat.drop_duplicates()

In [ ]:
#Create a new category "Unknown" for missinge genres
movie_dat['genres'].fillna('Unknown', inplace=True)

<ipython-input-36-7e4cca5d914c>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movie_dat['genres'].fillna('Unknown', inplace=True)
<ipython-input-36-7e4cca5d914c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_dat['genres'].fillna('Unknown', inplace=True)

In [ ]:
movie_dat.isnull().sum()

id                        0
title                     0
vote_average              0
vote_count                0
release_date          31407
overview                  0
original_language         0
genres                    0
keywords             533760
tagline              649998
revenue                   0
budget                    0
status                    0
popularity                0
null_count           768747
dtype: int64

In [ ]:
#Drop column null count
movie_dat.drop(columns=['null_count'], inplace=True)

<ipython-input-38-7f2a3b40ae30>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_dat.drop(columns=['null_count'], inplace=True)

In [ ]:
movie_dat.isnull().sum()

id                        0
title                     0
vote_average              0
vote_count                0
release_date          31407
overview                  0
original_language         0
genres                    0
keywords             533760
tagline              649998
revenue                   0
budget                    0
status                    0
popularity                0
dtype: int64

In [ ]:
movie_dat.shape

(800154, 14)

In [ ]:
# Drop column tagline as large portion is missing
movie_dat.drop(columns=['tagline'], inplace=True)

<ipython-input-47-ed9a1d7d050e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movie_dat.drop(columns=['tagline'], inplace=True)

In [ ]:
movie_dat.isnull().sum()

id                        0
title                     0
vote_average              0
vote_count                0
release_date          31407
overview                  0
original_language         0
genres                    0
keywords             533760
tagline              649998
revenue                   0
budget                    0
status                    0
popularity                0
dtype: int64

In [ ]:
# Export cleaned data
movie_dat.to_csv('/content/drive/MyDrive/dev/TMDB_movie_dataset_v12.csv', index=False)